# Generated by Django 3.2.6 on 2021-08-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tab',
            field=models.CharField(default='my title', max_length=255),
        ),
    ]
