# Generated by Django 3.2.6 on 2021-08-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_title_tab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_tab',
            field=models.CharField(max_length=255),
        ),
    ]
