# Generated by Django 3.2.6 on 2021-08-31 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210831_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
