# Generated by Django 3.2.6 on 2021-08-31 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_category1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
